### ISSUE TITLE
Was bedeutet das Feld Code

### ISSUE THREAD

**Issue by stritti** [sysbio-bioinf/CoCoV#1]
Für was ist das Feld Code in den Settings?
Ist das die Charge des Impfstoffs?

**Comment by fuerstberger** [comment]
Hallo @stritti ,
das "Code"-Feld ist ein optionales Feld, welches gegebenenfalls zur Aggregation oder Filterung verwendet werden kann. Es kann auch leer gelassen werden.

**Comment by stritti** [comment]
Ok, danke @fuerstberger.

Vielleicht könntet ihr das Feld dann auch ganz nach unten verschiedenen und als optional markieren?
Ist so ziemlich verwirrend.

**Comment by fuerstberger** [comment]
Danke für das Feedback @stritti .
Wir überlegen uns eine "optional"-Kennzeichnung für das Feld
